services:
  - docker

image: lazka/pygobject:pyenv

stages:
  - build_and_test
  - coverage

cache:
  paths:
    - _ccache/

.defaults: &defaults
  stage: build_and_test
  artifacts:
    paths:
      - coverage/
  script:
   - mkdir -p _ccache
   - export CCACHE_BASEDIR=${PWD}
   - export CCACHE_DIR=${PWD}/_ccache
   - bash -x ./.gitlab-ci/test-docker.sh

coverage:
  stage: coverage
  artifacts:
    paths:
      - coverage/
  variables:
    PYENV_VERSION: "3.6.4"
  script:
    - bash -x ./.gitlab-ci/coverage-docker.sh

python2-mingw32:
  stage: build_and_test
  tags:
    - win32
  variables:
    PYTHON: "python2"
    MSYSTEM: "MINGW32"
    CHERE_INVOKING: "yes"
  script:
    - C:\msys64\usr\bin\pacman --noconfirm -Syyuu --ask 20
    - C:\msys64\usr\bin\bash -lc "bash -x ./.gitlab-ci/test-msys2.sh"

python3-mingw32:
  stage: build_and_test
  tags:
    - win32
  variables:
    PYTHON: "python3"
    MSYSTEM: "MINGW32"
    CHERE_INVOKING: "yes"
  script:
    - C:\msys64\usr\bin\pacman --noconfirm -Syyuu --ask 20
    - C:\msys64\usr\bin\bash -lc "bash -x ./.gitlab-ci/test-msys2.sh"

python2.7:
  variables:
    PYENV_VERSION: "2.7.14"
  <<: *defaults

python3.4:
  variables:
    PYENV_VERSION: "3.4.7"
  <<: *defaults

python3.5:
  variables:
    PYENV_VERSION: "3.5.5"
  <<: *defaults

python3.6:
  variables:
    PYENV_VERSION: "3.6.4"
  <<: *defaults
